# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ricardo Ferreira
email: rmf2pt@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a father of three amazing kids, husband of one loving wife, 
  accountant, lifelong learner, rubyist and web developer. 
  I’m currently focusing my work in Ruby on Rails. 
  I’m open for new projects in my expertise and I will help you with your own site. 
  Get in touch with me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rmf2pt.com" # the base hostname & protocol for your site
twitter_username: rmf2pt
github_username:  rmf2pt

# Build settings
markdown: kramdown
